### ISSUE TITLE
升级0.7.2后选择范围问题

### ISSUE THREAD

**Issue by coffe6591** [luojilab/DDEasyMarker#15]
升级0.7.2后选择范围超过一行（0.71正常），颜色渲染只能覆盖一行。对js不太熟悉，没深入看原因。最近学react-native，想把它放到rn。插件会支持全平台吗

**Comment by lihaonanGY** [comment]
rect颜色渲染计算不准问题已在0.7.4得到解决，刚好是你提issue的前一天解决的。

关于rn可能暂时不能支持，实现思路上还是基于html在操作dom。

**Comment by coffe6591** [comment]
首先，谢谢。
我之前不知道有selection的api。做的时候完全闷逼。
看了你的项目才知道方向。我已经用了webbiew先把功能实现了。后期我慢慢把东西挪到react-native。
