### ISSUE TITLE
如何保存高亮信息到数据库？

### ISSUE THREAD

**Issue by gzm1997** [luojilab/DDEasyMarker#21]
您好，我使用你们的easyMarker发现，高亮的api是：
his.highlightLine
这个api的第一个参数是一个selection对象，如下：
![image](https://user-images.githubusercontent.com/15107912/69841420-fc468e00-1299-11ea-9745-3e965a64f4a2.png)

但是如果我想将高亮的信息存到数据库 就是想将这个selection对象存到oracle数据库，那么我们可以再怎么做呢？谢谢。

**Comment by zy20113377** [comment]
解决方案：
https://github.com/luojilab/easy-marker/issues/66#issuecomment-1640141611
