### ISSUE TITLE
勤问iframe里面内容  无法拖动选中文字该怎么解决呢

### ISSUE THREAD

**Issue by JERSONLEIBOY** [luojilab/DDEasyMarker#58]

**Comment by lihaonanGY** [comment]
已协助解决

**Comment by leejunhui** [comment]
@lihaonanGY 你好，我也遇到了在 iframe 中无法选择文字，可以请教一下最后是怎么解决的吗？

**Comment by leejunhui** [comment]
![image](https://user-images.githubusercontent.com/9007793/202951154-46f4e51a-e2b8-4ddd-9a8e-253494f7d40a.png)
经过断点调试，定位到在执行 moveCursor 方法的时候，传入  element 是 iframe，导致 getClickPosition 方法接收到 element 和 x，y 坐标后返回的是 null

**Comment by leejunhui** [comment]
在 `handleTouchMoveThrottle` 方法中 `const target = document.elementFromPoint(x, y)` 会得到 `target` 为 `iframe`，在 google 之后发现可以这样优化一下：
```
if (el instanceof HTMLIFrameElement)
    el = el.contentWindow.document.elementFromPoint(x, y);  //Not sure if you need to update x, y to account for being inside another dom
```
[solution - stackoverflow](https://stackoverflow.com/a/8811344)

**Comment by leejunhui** [comment]
![4l7oz-96ut1](https://user-images.githubusercontent.com/9007793/202954981-c0e72cc2-7a8d-4f69-8e3c-75e2c214669c.gif)
上面的方案亲测可用~
